In [2]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [10]:
import pystruct
from sklearn.datasets import load_iris
from sklearn.cross_validation import train_test_split

## Multi-Class SVM

In [5]:
iris = load_iris()

In [8]:
print iris.data

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5

In [9]:
print iris.target

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [11]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.4, random_state=0)

In [14]:
from pystruct.learners import NSlackSSVM
from pystruct.models import MultiClassClf
clf = NSlackSSVM(MultiClassClf())

In [15]:
clf.fit(X_train, y_train)

NSlackSSVM(C=1.0, batch_size=100, break_on_bad=False, check_constraints=True,
      inactive_threshold=1e-05, inactive_window=50, logger=None,
      max_iter=100, model=MultiClassClf(n_features=4, n_classes=3),
      n_jobs=1, negativity_constraint=None, show_loss_every=0,
      switch_to=None, tol=0.001, verbose=0)

In [16]:
clf.predict(X_test)

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1, 0,
       0, 2, 0, 0, 1, 1, 0, 2, 2, 0, 2, 2, 1, 0, 2, 1, 1, 2, 0, 2, 0, 0, 1,
       2, 2, 2, 2, 1, 2, 1, 1, 2, 2, 2, 2, 1, 2])

In [17]:
clf.score(X_test, y_test)

0.96666666666666667

## Multilabel SVM

In [18]:
from pystruct.datasets import load_scene
scene = load_scene()

In [22]:
X_train, X_test = scene['X_train'], scene['X_test']
y_train, y_test = scene['y_train'], scene['y_test']

In [27]:
y_test

array([[1, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       ..., 
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1]])

In [28]:
from pystruct.models import MultiLabelClf

In [31]:
clf = NSlackSSVM(MultiLabelClf())

In [32]:
clf.fit(X_train, y_train)

NSlackSSVM(C=1.0, batch_size=100, break_on_bad=False, check_constraints=True,
      inactive_threshold=1e-05, inactive_window=50, logger=None,
      max_iter=100,
      model=MultiLabelClf(n_states: 2, inference_method: ad3), n_jobs=1,
      negativity_constraint=None, show_loss_every=0, switch_to=None,
      tol=0.001, verbose=0)

In [33]:
clf.score(X_test, y_test)

0.86552396878483839

## ChrainCRF

In [40]:
from pystruct.datasets import load_letters

In [41]:
letters = load_letters()

In [56]:
X, y, folds = letters['data'], letters['labels'], letters['folds']

In [61]:
X, y = np.array(X), np.array(y)

In [65]:
X_train, X_test = X[folds == 1], X[folds != 1]
y_train, y_test = y[folds == 1], y[folds != 1]

In [68]:
from pystruct.models import ChainCRF
from pystruct.learners import FrankWolfeSSVM

In [69]:
model = ChainCRF()
ssvm = FrankWolfeSSVM(model=model, C=.1, max_iter=10)

In [70]:
ssvm.fit(X_train, y_train)

FrankWolfeSSVM(C=0.1, batch_mode=False, check_dual_every=10,
        do_averaging=True, line_search=True, logger=None, max_iter=10,
        model=ChainCRF(n_states: 26, inference_method: max-product),
        n_jobs=1, random_state=None, sample_method='perm',
        show_loss_every=0, tol=0.001, verbose=0)

In [71]:
ssvm.score(X_test, y_test)

0.78713897855783821

In [72]:
features, y, folds = letters['data'], letters['labels'], letters['folds']
features, y = np.array(features), np.array(y)
features_train, features_test = features[folds == 1], features[folds != 1]
y_train, y_test = y[folds == 1], y[folds != 1]

In [73]:
f_t = features_train
X_train = [(features_i, np.vstack([np.arange(features_i.shape[0] - 1), np.arange(1, features_i.shape[0])]))
           for features_i in f_t]

In [74]:
from pystruct.models import GraphCRF

In [75]:
model = GraphCRF(directed=True, inference_method="max-product")
ssvm = FrankWolfeSSVM(model=model, C=.1, max_iter=10)

In [76]:
ssvm.fit(X_train, y_train) 

FrankWolfeSSVM(C=0.1, batch_mode=False, check_dual_every=10,
        do_averaging=True, line_search=True, logger=None, max_iter=10,
        model=GraphCRF(n_states: 26, inference_method: max-product),
        n_jobs=1, random_state=None, sample_method='perm',
        show_loss_every=0, tol=0.001, verbose=0)

In [79]:
X_test = [(features_i, np.vstack([np.arange(features_i.shape[0] - 1), np.arange(1, features_i.shape[0])]))
           for features_i in features_test]

In [80]:
ssvm.score(X_test, y_test)

0.74260854693545975